{{- if .Values.storage.cubeApi.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cubeapi-pvc
  namespace: {{ .Values.namespace }}
spec:
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
  accessModes:
    - {{ .Values.storage.cubeApi.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.cubeApi.size }}
{{- end }}